### ISSUE TITLE
DecimalCollection mejora multiply()

### ISSUE THREAD

**Issue by DiegoRiofrio** [DiegoRiofrio/IWVG.SwC.DiegoRiofrio#1]
[wiki DecimalCollection](https://github.com/DiegoRiofrio/IWVG.SwC.DiegoRiofrio/wiki/DecimalCollection)

Hito:30/09/2018

**Comment by jolomoreno** [comment]
Hola, ya he terminado el issue, la rama está mergeada con develop. También se ha subido a remoto tanto la rama develop como la issue#01. 
He comprobado que en Travis CI se ha ejecutado bien la compilación así que por mi parte la tarea queda cerrada.
Un saludo!
